### ISSUE TITLE
Changed source on MS websites?

### ISSUE THREAD

**Issue by SoehnelS** [slavizh/Get-SCOMManagementPacks#8]
Hallo!
Thanks for the script!

I find out, the Version and Published values are not well extracted, maybe the html source changed by Microsoft.

I use this changes to let it work again (within #SoehnelS -> #<- SoehnelS):
function Get-MSDownloadVersionDetails
{
    [CmdletBinding()]
    param
    (
        [Parameter( Mandatory = $true )]
        [string]
        $URI
    )

    begin {}

    process
    {
        $HTTPData = Get-URIData -URI $URI

        if ($HTTPData.Status -ne "Error")
        {
            $Status = "Success"
            if ($HTTPData -match 'Version:</span></div><p>(.+?)</p></div>')
            {
                $MPVersion = $matches[1].Replace("?","").TrimEnd()
           #Soehnels ->
            }elseif($HTTPData -match 'Version:(.+?)</div><p>(.+?)</p></div>'){
                $MPVersion = $matches[2].Replace("?","").TrimEnd()
           #<- Soehnels
            }

            if ($HTTPData -match 'Date Published:</span></div><p>(.+?)</p></div>')
            {
                $MPPublishDate = $matches[1].Replace("/","-").TrimEnd()
           #Soehnels ->
            }elseif($HTTPData -match 'Date Published:(.+?)</div><p>(.+?)</p></div>'){
                $MPPublishDate = $matches[2].Replace("/","-").TrimEnd()
           #<- Soehnels
            }

        }
        else
        {
            $MPVersion = ""
            $MPPublishDate = ""
            $Status = "Error: " + $HTTPData.PageData
        }

        New-Object -TypeName PSObject -Property @{
            MSDLVersion = $MPVersion
            MSDLReleaseDate = $MPPublishDate
            Status = $Status
        }
    }

    end
    {}
}

**Comment by MSFTZombie** [comment]
Looks like the webpages have spaces between "Version:" and "Date Published:" and removed "</span>" on their new download sites. There are a number of pages that are still using the old format. 

If you add the following it will work - "BizTalk 2013 R2" due to the date format invalid, but not worried about that one.



`



        $HTTPData = Get-URIData -URI $URI

        if ($HTTPData.Status -ne "Error")
        {
            $Status = "Success"

            if ($HTTPData -match 'Version:\s*</div><p>(.+?)</p></div>')
            {
                $MPVersion = $matches[1].Replace("?","").TrimEnd()
            }

            if ($HTTPData -match 'Date Published:\s*</div><p>(.+?)</p></div>')
            {
                $MPPublishDate = $matches[1].Replace("/","-").TrimEnd()
            }


            if ($HTTPData -match 'Version:</span></div><p>(.+?)</p></div>')
            {
                $MPVersion = $matches[1].Replace("?","").TrimEnd()
            }

            if ($HTTPData -match 'Date Published:</span></div><p>(.+?)</p></div>')
            {
                $MPPublishDate = $matches[1].Replace("/","-").TrimEnd()
            }


        }`
Lynne Taggart - MSFT
https://blogs.technet.microsoft.com/allthat/2017/12/08/fixed-get-scommanagementpacks-ps1/

**Comment by SoehnelS** [comment]
Thanks!
