### ISSUE TITLE
HTTP Data parsing

### ISSUE THREAD

**Issue by CoenvanDijk** [slavizh/Get-SCOMManagementPacks#9]
if ($HTTPData -match 'Version:</span></div><p>(.+?)</p></div>')
            {
                $MPVersion = $matches[1].Replace("?","").TrimEnd()
            }

            if ($HTTPData -match 'Date Published:</span></div><p>(.+?)</p></div>')
            {
                $MPPublishDate = $matches[1].Replace("/","-").TrimEnd()
            }

should be changed to

            if ($HTTPData -match 'Version:[ ]{1,}</div><p>(.+?)</p></div>') 
            { 
                $MPVersion=$matches[1].Replace("?","").Trimend() 
            } 
 
 
            if ($HTTPData -match 'Date Published:[ ]{1,}</div><p>(.+?)</p></div>') 
            { 
                $MPPublishDate=$matches[1].Replace("/","-").Trimend() 
            }

**Comment by slavizh** [comment]
This should have been fixed in 4.4 release. We had already another person offering a solution.
